version: '2'

services:
  django:
    container_name: squid_backend
    build:
      context: .
      dockerfile: ./docker/django/local/Dockerfile
    command: /start.sh
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  node:
    container_name: squid_frontend
    build:
      context: .
      dockerfile: ./docker/node/local/Dockerfile
    command: /start.sh
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
